name: Build

on:
  push:
    branches: [master, v**.**]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npx docusaurus build
      - name: "Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: sed-manager-website
          path: ${{ github.workspace }}/build
          if-no-files-found: error
