name: Deploy

on:
  workflow_run:
    workflows: [Build]
    branches: [v**.**]
    types: [completed]

jobs:
  deploy:
    permissions:
      actions: read
      pages: write
      id-token: write

    env:
      GH_TOKEN: ${{ github.token }}

    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch != null }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: sed-manager-website
          path: ${{github.workspace}}/build
          github-token: ${{github.token}}
          run-id: ${{ github.event.workflow_run.id }}

      # Yeah, this if fucking dumb, but I don't know how to specify the
      # artifact from another workflow to actions/deploy-pages.
      - name: Reupload as pages-artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
            name: sed-manager-website
            path: ${{github.workspace}}/build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
            artifact_name: sed-manager-website